/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as BrowseRouteImport } from './routes/browse'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProvidersIdRouteImport } from './routes/providers.$id'
import { Route as BookIdRouteImport } from './routes/book.$id'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseRoute = BrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProvidersIdRoute = ProvidersIdRouteImport.update({
  id: '/providers/$id',
  path: '/providers/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BookIdRoute = BookIdRouteImport.update({
  id: '/book/$id',
  path: '/book/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/browse': typeof BrowseRoute
  '/dashboard': typeof DashboardRoute
  '/book/$id': typeof BookIdRoute
  '/providers/$id': typeof ProvidersIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/browse': typeof BrowseRoute
  '/dashboard': typeof DashboardRoute
  '/book/$id': typeof BookIdRoute
  '/providers/$id': typeof ProvidersIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/browse': typeof BrowseRoute
  '/dashboard': typeof DashboardRoute
  '/book/$id': typeof BookIdRoute
  '/providers/$id': typeof ProvidersIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/browse' | '/dashboard' | '/book/$id' | '/providers/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/browse' | '/dashboard' | '/book/$id' | '/providers/$id'
  id:
    | '__root__'
    | '/'
    | '/browse'
    | '/dashboard'
    | '/book/$id'
    | '/providers/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BrowseRoute: typeof BrowseRoute
  DashboardRoute: typeof DashboardRoute
  BookIdRoute: typeof BookIdRoute
  ProvidersIdRoute: typeof ProvidersIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse': {
      id: '/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof BrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/providers/$id': {
      id: '/providers/$id'
      path: '/providers/$id'
      fullPath: '/providers/$id'
      preLoaderRoute: typeof ProvidersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/$id': {
      id: '/book/$id'
      path: '/book/$id'
      fullPath: '/book/$id'
      preLoaderRoute: typeof BookIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BrowseRoute: BrowseRoute,
  DashboardRoute: DashboardRoute,
  BookIdRoute: BookIdRoute,
  ProvidersIdRoute: ProvidersIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
