/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SafetyRouteImport } from './routes/safety'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BrowseRouteImport } from './routes/browse'
import { Route as BecomeAProviderRouteImport } from './routes/become-a-provider'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AgeVerificationRouteImport } from './routes/age-verification'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProvidersIdRouteImport } from './routes/providers.$id'
import { Route as BookIdRouteImport } from './routes/book.$id'
import { Route as ApiPublicWebhooksDiditRouteImport } from './routes/api/public/webhooks/didit'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SafetyRoute = SafetyRouteImport.update({
  id: '/safety',
  path: '/safety',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseRoute = BrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => rootRouteImport,
} as any)
const BecomeAProviderRoute = BecomeAProviderRouteImport.update({
  id: '/become-a-provider',
  path: '/become-a-provider',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AgeVerificationRoute = AgeVerificationRouteImport.update({
  id: '/age-verification',
  path: '/age-verification',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProvidersIdRoute = ProvidersIdRouteImport.update({
  id: '/providers/$id',
  path: '/providers/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BookIdRoute = BookIdRouteImport.update({
  id: '/book/$id',
  path: '/book/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebhooksDiditRoute = ApiPublicWebhooksDiditRouteImport.update({
  id: '/api/public/webhooks/didit',
  path: '/api/public/webhooks/didit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/age-verification': typeof AgeVerificationRoute
  '/auth': typeof AuthRoute
  '/become-a-provider': typeof BecomeAProviderRoute
  '/browse': typeof BrowseRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/faq': typeof FaqRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/safety': typeof SafetyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/book/$id': typeof BookIdRoute
  '/providers/$id': typeof ProvidersIdRoute
  '/api/public/webhooks/didit': typeof ApiPublicWebhooksDiditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/age-verification': typeof AgeVerificationRoute
  '/auth': typeof AuthRoute
  '/become-a-provider': typeof BecomeAProviderRoute
  '/browse': typeof BrowseRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/faq': typeof FaqRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/safety': typeof SafetyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/book/$id': typeof BookIdRoute
  '/providers/$id': typeof ProvidersIdRoute
  '/api/public/webhooks/didit': typeof ApiPublicWebhooksDiditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/age-verification': typeof AgeVerificationRoute
  '/auth': typeof AuthRoute
  '/become-a-provider': typeof BecomeAProviderRoute
  '/browse': typeof BrowseRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/faq': typeof FaqRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/safety': typeof SafetyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/book/$id': typeof BookIdRoute
  '/providers/$id': typeof ProvidersIdRoute
  '/api/public/webhooks/didit': typeof ApiPublicWebhooksDiditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/age-verification'
    | '/auth'
    | '/become-a-provider'
    | '/browse'
    | '/contact'
    | '/dashboard'
    | '/faq'
    | '/pricing'
    | '/privacy'
    | '/safety'
    | '/sitemap.xml'
    | '/terms'
    | '/book/$id'
    | '/providers/$id'
    | '/api/public/webhooks/didit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/age-verification'
    | '/auth'
    | '/become-a-provider'
    | '/browse'
    | '/contact'
    | '/dashboard'
    | '/faq'
    | '/pricing'
    | '/privacy'
    | '/safety'
    | '/sitemap.xml'
    | '/terms'
    | '/book/$id'
    | '/providers/$id'
    | '/api/public/webhooks/didit'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/age-verification'
    | '/auth'
    | '/become-a-provider'
    | '/browse'
    | '/contact'
    | '/dashboard'
    | '/faq'
    | '/pricing'
    | '/privacy'
    | '/safety'
    | '/sitemap.xml'
    | '/terms'
    | '/book/$id'
    | '/providers/$id'
    | '/api/public/webhooks/didit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AgeVerificationRoute: typeof AgeVerificationRoute
  AuthRoute: typeof AuthRoute
  BecomeAProviderRoute: typeof BecomeAProviderRoute
  BrowseRoute: typeof BrowseRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  FaqRoute: typeof FaqRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  SafetyRoute: typeof SafetyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  BookIdRoute: typeof BookIdRoute
  ProvidersIdRoute: typeof ProvidersIdRoute
  ApiPublicWebhooksDiditRoute: typeof ApiPublicWebhooksDiditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/safety': {
      id: '/safety'
      path: '/safety'
      fullPath: '/safety'
      preLoaderRoute: typeof SafetyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse': {
      id: '/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof BrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/become-a-provider': {
      id: '/become-a-provider'
      path: '/become-a-provider'
      fullPath: '/become-a-provider'
      preLoaderRoute: typeof BecomeAProviderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/age-verification': {
      id: '/age-verification'
      path: '/age-verification'
      fullPath: '/age-verification'
      preLoaderRoute: typeof AgeVerificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/providers/$id': {
      id: '/providers/$id'
      path: '/providers/$id'
      fullPath: '/providers/$id'
      preLoaderRoute: typeof ProvidersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/$id': {
      id: '/book/$id'
      path: '/book/$id'
      fullPath: '/book/$id'
      preLoaderRoute: typeof BookIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/didit': {
      id: '/api/public/webhooks/didit'
      path: '/api/public/webhooks/didit'
      fullPath: '/api/public/webhooks/didit'
      preLoaderRoute: typeof ApiPublicWebhooksDiditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AgeVerificationRoute: AgeVerificationRoute,
  AuthRoute: AuthRoute,
  BecomeAProviderRoute: BecomeAProviderRoute,
  BrowseRoute: BrowseRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  FaqRoute: FaqRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  SafetyRoute: SafetyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  BookIdRoute: BookIdRoute,
  ProvidersIdRoute: ProvidersIdRoute,
  ApiPublicWebhooksDiditRoute: ApiPublicWebhooksDiditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
